parameters:
  bazar_farm_id: 1100
  yeswiki-farm-root-folder: '.'
  contact_wikis:
    default_template: 'list-email.twig'
  yeswiki_symlinked_files:
  # this can remplace files and folders from yeswiki_empty_folders and yeswiki_files
  # by symlinking from the main wiki folder
  # - 'custom'
  yeswiki_empty_folders:
    - 'cache'
    - 'custom'
    - 'files'
    - 'private'
  yeswiki_files:
    - 'index.php'
    - 'composer.json'
    - 'composer.lock'
    - 'Dockerfile'
    - 'docker-compose.yml'
    - 'INSTALL.md'
    - 'interwiki.conf'
    - 'LICENSE'
    - 'README.md'
    - 'robots.txt'
    - 'wakka.basic.css'
    - 'wakka.css'
    - 'wakka.php'
    - 'yeswicli'
    - 'actions'
    - 'docs'
    - 'docker'
    - 'files/AdaLovelace_ada_byron.jpg'
    - 'files/ElizabethJFeinler_elizabethfeinler.jpg'
    - 'files/yeswiki-logo.png'
    - 'files/ElizabethJFeinler_elizabethfeinler-2011.jpg'
    - 'files/GererSite_modele_19880101000000_23001231235959.jpg'
    - 'files/LovelaceAda_lovelace.png'
    - 'files/PageHeader_bandeau_19880101000000_23001231235959.png'
    - 'files/PageHeader_bandeau_19880101000000_23001231235959.webp'
    - 'files/TesT2_presence-photo.png'
    - 'files/UnBeauLogoPourYeswiki_yeswiki-logo.png'
    - 'files/UnNouveauThemePourYeswiki_capture-décran-2020-02-12-à-13.16.33.png'
    - 'files/YeswikidaY_yeswiki-logo.png'
    - 'formatters'
    - 'handlers'
    - 'includes'
    - 'javascripts'
    - 'lang'
    - 'setup'
    - 'styles'
    - 'templates'
    - 'tests'
    - 'themes/margot'
    - 'tools/aceditor'
    - 'tools/attach'
    - 'tools/autoupdate'
    - 'tools/bazar'
    - 'tools/contact'
    - 'tools/helloworld'
    - 'tools/lang'
    - 'tools/login'
    - 'tools/progressBar'
    - 'tools/rss'
    - 'tools/security'
    - 'tools/syndication'
    - 'tools/tableau'
    - 'tools/tags'
    - 'tools/templates'
    - 'tools/toc'
    - 'tools/README.md'
    - 'vendor'
  # for edit config action
  ferme_editable_config_params:
    - 'bazar_farm_id'
    - 'yeswiki-farm-root-folder'
    - 'yeswiki-farm-root-url'
    - 'yeswiki-farm-admin-name'
    - 'yeswiki-farm-admin-pass'
    - 'yeswiki-farm-extra-themes'
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Ferme\Service\:
    resource: 'services/*'
